# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='user_id',
            field=models.ManyToManyField(related_name='wishuserid', to='wish.Users'),
        ),
    ]
